-- Utility Hub initial schema
create extension if not exists pgcrypto;

create table if not exists public.api_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  prefix text not null,
  key_hash text not null,
  rate_limit_per_minute integer not null default 60,
  last_used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, prefix)
);

create table if not exists public.files (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_key text not null unique,
  filename text not null,
  content_type text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  sha256 text,
  source text not null default 'upload',
  created_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  app_id text not null,
  input_file_id uuid not null references public.files(id) on delete restrict,
  status text not null default 'queued' check (status in ('queued', 'processing', 'completed', 'failed')),
  progress integer not null default 0 check (progress >= 0 and progress <= 100),
  options jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  result_file_id uuid references public.files(id) on delete set null,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  api_key_id uuid references public.api_keys(id) on delete set null,
  event_type text not null,
  resource_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  request_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_api_keys_user_id on public.api_keys(user_id);
create index if not exists idx_api_keys_prefix on public.api_keys(prefix);
create index if not exists idx_api_keys_revoked_at on public.api_keys(revoked_at);

create index if not exists idx_files_user_id_created_at on public.files(user_id, created_at desc);
create index if not exists idx_jobs_user_id_created_at on public.jobs(user_id, created_at desc);
create index if not exists idx_jobs_status_created_at on public.jobs(status, created_at asc);
create index if not exists idx_usage_events_user_event_created on public.usage_events(user_id, event_type, created_at desc);
create index if not exists idx_usage_events_key_event_created on public.usage_events(api_key_id, event_type, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_jobs_set_updated_at on public.jobs;
create trigger trg_jobs_set_updated_at
before update on public.jobs
for each row
execute function public.set_updated_at();

alter table public.api_keys enable row level security;
alter table public.files enable row level security;
alter table public.jobs enable row level security;
alter table public.usage_events enable row level security;

-- API keys policies
create policy "api_keys_select_own"
on public.api_keys
for select
using (auth.uid() = user_id);

create policy "api_keys_insert_own"
on public.api_keys
for insert
with check (auth.uid() = user_id);

create policy "api_keys_update_own"
on public.api_keys
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "api_keys_delete_own"
on public.api_keys
for delete
using (auth.uid() = user_id);

-- Files policies
create policy "files_select_own"
on public.files
for select
using (auth.uid() = user_id);

create policy "files_insert_own"
on public.files
for insert
with check (auth.uid() = user_id);

create policy "files_update_own"
on public.files
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "files_delete_own"
on public.files
for delete
using (auth.uid() = user_id);

-- Jobs policies
create policy "jobs_select_own"
on public.jobs
for select
using (auth.uid() = user_id);

create policy "jobs_insert_own"
on public.jobs
for insert
with check (auth.uid() = user_id);

create policy "jobs_update_own"
on public.jobs
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "jobs_delete_own"
on public.jobs
for delete
using (auth.uid() = user_id);

-- Usage events policies
create policy "usage_events_select_own"
on public.usage_events
for select
using (auth.uid() = user_id);

create policy "usage_events_insert_own"
on public.usage_events
for insert
with check (auth.uid() = user_id);

create policy "usage_events_update_own"
on public.usage_events
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "usage_events_delete_own"
on public.usage_events
for delete
using (auth.uid() = user_id);
